import { Geist_Mono,  Geist } from "next/font/google";
import "./globals.css";
import PageTransition from "@/components/ui/PageTransition";

import Header from "@/components/ui/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
