import { Geist_Mono,  Geist } from "next/font/google";
import { Plus_Jakarta_Sans } from 'next/font/google';
import { Inter_Tight } from 'next/font/google';
import { Manrope } from 'next/font/google';
import "./globals.css";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import Header from "@/components/Header";
import { GridPattern } from "@/components/ui/grid-pattern";
import { Analytics } from "@vercel/analytics/next"


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ['latin'],
  weight: ['400', '600', '700', '800']
})

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ['latin'],
  weight: ['400', '600', '700', '800']
})


const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ['latin'],
  weight: ['400', '600', '700', '800']
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} relative`}>
        <div className="fixed inset-0 -z-10">
          <GridPattern className="fill-white/[0.03] stroke-white/[0.03]" />
        </div>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
        <Analytics />
      </body>
    </html>
  );
}
